language: node_js
node_js:
  - "10"
before_install:
  - sudo apt-get install -y libpng-dev autoconf libtool nasm
branches:
  only:
  - master
jobs:
  include:
    - stage: Test
      script:
        - npm test
    - stage: Deploy
      before_script:
        - npm install -g firebase-tools gulp-cli
      script:
        - gulp --env production build
      after_success:
        - firebase deploy --token $FIREBASE_TOKEN --project francisco-carmona-portfolio

